[general]
creation_date = "07/25/2023, 14:42:20"
model = "conv_lstm"

[model_params]
size = 64
kmer_len = 9
num_out = 2

[modbases]
mod_bases = "a"
offset = 0
mod_long_names_0 = "6mA"
chunk_context_0 = 50
chunk_context_1 = 50
kmer_context_bases_0 = 4
kmer_context_bases_1 = 4
motif = "GATC"
motif_offset = 1

[refinement]
refine_do_rough_rescale = 1
refine_kmer_center_idx = 2
